config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'

  get 'pages/location'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def location
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleUdemy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper green darken-1">
        <a href="#!" class="brand-logo">Udemo</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
          <li><a href="#">Courses</a></li>
          <li><a href="<%= pages_about_path %>">About</a></li>
          <li><%= link_to "Location", pages_location_path %></li>
        </ul>
      </div>  
    </nav>
    
    <ul class="sidenav" id="mobile-demo">
      <li><a href="#">Courses</a></li>
      <li><a href="<%= pages_about_path %>">About</a></li>
      <li><%= link_to "Location", pages_location_path %></li>
    </ul>

    <div class="row">
      <div class="col m10 offset-m1">
        <%= yield %>
      </div>
    </div>
  
    <script>
      $(document).ready(function(){
        $('.sidenav').sidenav();
      });
    </script>
  </body>
</html>

app/views/pages/about.html.erb
<h2>About</h2>

<div class="card z-depth-3">
    <div class="card-content white-text">
        <div class="row">
            <div class="col m6">
                <a class="twitter-timeline" data-height="400" href="https://twitter.com/TwitterDev?ref_src=twsrc%5Etfw">Tweets by TwitterDev</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </div>
            
            <div class="col m6">
                <div class="card-panel teal lighten-1 z-depth-1">
                    <div class="row">
                        <div class="col m3">
                            <%= image_tag "avatar.jpg", class: "circle responsive-img" %>
                        </div>
                        <div class="col m9">
                            <span class="white-text">
                                <h5>Liana Liberato</h5>
                                Lorem Ipsum is simply dummy text of the printing and typesetting 
                                industry. Lorem Ipsum has been the industry's standard dummy text 
                                ever since the 1500s, when an unknown printer took a galley of 
                                type and scrambled it to make a type specimen book. It has survived 
                                not only five centuries, but also the leap into electronic typesetting, 
                                remaining essentially unchanged. It was popularised in the 1960s with the 
                                
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/location.html.erb
<h2>Location</h2>

<div class="card z-depth-3">
    <div class="card-content black-text">
        <div class="row">
            You can find me here:<br/>
        </div>
        <iframe
            width="600"
            height="450"
            style="border:0"
            loading="lazy"
            allowfullscreen
            src="https://www.google.com/maps/embed/v1/place?key=AIzaSyArnWRlCxteegRtu4IgzOpqmrzEpktMRmM
                &q=Melbourne+Central,VIC">
        </iframe>
    </div>
</div>